name: PsychroAn_tuto-env

channels:
  - conda-forge

dependencies:
  - python=3.8.8
  - jupyter=1.0.0
  - jupyterlab=3.0.14
  - ipywidgets=7.5.1
  - matplotlib=3.4.1
  - numpy=1.20.2
  - scipy=1.6.2
  - pandas=1.2.4
  - voila=0.2.16

  - alembic=1.7.5
  - alsa-lib=1.2.3 
  - anyio=3.5.0 
  - argon2-cffi=21.3.0 
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5 
  - async_generator=1.10
  - attrs=21.4.0
  - babel=2.9.1 
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - black=21.12b0 
  - bleach=4.1.0 
  - blinker=1.4 
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates=2021.10.8 
  - certify=2021.10.8 
  - certipy=0.1.3
  - cffi=1.14.6
  - charset-normalizer=2.0.10
  - click=8.0.3
  - cryptography=36.0.1 
  - cycler=0.11.0 
  - dataclasses=0.8
  - dbus=1.13.6 
  - debugpy=1.5.1 
  - decorator=5.1.1
  - defusedxml=0.7.1 
  - deprecation=2.1.0 
  - entrypoints=0.3 
  - executing=0.8.2 
  - expat=2.4.8
  - flit-core=3.6.0
  - fontconfig=2.14.0
  - freetype=2.10.4
  - fribidi=1.0.10
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.68.4
  - glib-tools=2.68.4
  - greenlet=1.1.2
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - icu=68.2 
  - idna=3.3
  - importlib-metadata=4.10.1
  - importlib_resources=5.4.0
  - ipykernel=6.7.0
  - ipython=8.0.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1 
  - jbig=2.1
  - jedi=0.18.1
  - jinja2=3.0.3
  - jpeg=9e
  - json5=0.9.5
  - jsonschema=4.4.0 
  - jupyter=1.0.0
  - jupyter-offlinenotebook=0.2.2
  - jupyter-packaging=0.12.0
  - jupyter-resource-usage=0.6.1
  - jupyter_client=6.1.12
  - jupyter_console=6.4.2
  - jupyter_core=4.9.1
  - jupyter_server=1.13.4
  - jupyter_telemetry=0.1.0
  - jupyterhub-base=1.4.2
  - jupyterhub-singleuser=1.4.2
  - jupyterlab=3.0.14
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.3
  - jupyterlab_widgets=1.0.2
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
