name: PsycAn_cool-env

channels:
  - conda-forge

dependencies:
  - python=3.0.7
  - jupyter=1.0.0
  - jupyterlab=3.2.1
  - jupyterlab-widgets=1.0.0
  - ipywidgets=7.6.5
  - matplotlib=3.4.3
  - numpy=1.20.3
  - scipy=1.7.3
  - pandas=1.3.4
  - voila=0.2.16
